import type { Account, Guest, Hotel, Reservation, Room } from './pms-types';

export const HOTEL: Hotel = {
  id: 'h1',
  name: 'Varshana Hotel',
  operationalDate: '2026-09-15',
};

export const INITIAL_ROOMS: Room[] = [
  { id: 'r01', number: 'UH 01', type: 'Apartamento', floor: 1, block: 'Torre A', capacity: 2, occupancy: 'ocupado', governance: 'limpo', housekeeper: 'Maria Silva' },
  { id: 'r02', number: 'UH 02', type: 'Standard', floor: 1, block: 'Torre A', capacity: 2, occupancy: 'livre', governance: 'limpo', housekeeper: 'Maria Silva' },
  { id: 'r03', number: 'UH 03', type: 'Superior', floor: 1, block: 'Torre A', capacity: 2, occupancy: 'ocupado', governance: 'limpo', housekeeper: 'Ana Costa' },
  { id: 'r04', number: 'UH 04', type: 'Standard', floor: 1, block: 'Torre A', capacity: 2, occupancy: 'livre', governance: 'limpo' },
  { id: 'r05', number: 'UH 05', type: 'Apartamento', floor: 1, block: 'Torre A', capacity: 3, occupancy: 'ocupado', governance: 'sujo', housekeeper: 'Ana Costa' },
  { id: 'r06', number: 'UH 06', type: 'Standard', floor: 1, block: 'Torre A', capacity: 2, occupancy: 'bloqueado', governance: 'interditado', notes: 'Vazamento banheiro', blockedReason: 'Vazamento banheiro' },
  { id: 'r07', number: 'UH 07', type: 'Superior', floor: 2, block: 'Torre A', capacity: 2, occupancy: 'ocupado', governance: 'limpo', housekeeper: 'Joana Pereira' },
  { id: 'r08', number: 'UH 08', type: 'Standard', floor: 2, block: 'Torre A', capacity: 2, occupancy: 'ocupado', governance: 'limpo', housekeeper: 'Joana Pereira' },
  { id: 'r09', number: 'UH 09', type: 'Suite', floor: 2, block: 'Torre B', capacity: 3, occupancy: 'livre', governance: 'inspecao', housekeeper: 'Fernanda Lima' },
  { id: 'r10', number: 'UH 10', type: 'Standard', floor: 2, block: 'Torre B', capacity: 2, occupancy: 'livre', governance: 'limpo' },
  { id: 'r11', number: 'UH 11', type: 'Chalé Master', floor: 0, block: 'Chalés', capacity: 4, occupancy: 'livre', governance: 'limpo', housekeeper: 'Patrícia Souza' },
  { id: 'r12', number: 'UH 12', type: 'Chalé Master', floor: 0, block: 'Chalés', capacity: 4, occupancy: 'ocupado', governance: 'limpo', housekeeper: 'Patrícia Souza' },
  { id: 'r13', number: 'UH 13', type: 'Chalé Master', floor: 0, block: 'Chalés', capacity: 4, occupancy: 'livre', governance: 'limpo' },
  { id: 'r14', number: 'UH 14', type: 'Bangalô', floor: 0, block: 'Chalés', capacity: 3, occupancy: 'bloqueado', governance: 'manutencao', notes: 'Ar-condicionado', blockedReason: 'Ar-condicionado' },
  { id: 'r15', number: 'UH 15', type: 'Bangalô', floor: 0, block: 'Chalés', capacity: 3, occupancy: 'livre', governance: 'limpo' },
  { id: 'r16', number: 'UH 16', type: 'Apartamento', floor: 2, block: 'Torre B', capacity: 3, occupancy: 'ocupado', governance: 'limpo', housekeeper: 'Fernanda Lima' },
  { id: 'r17', number: 'UH 17', type: 'Bangalô', floor: 0, block: 'Chalés', capacity: 3, occupancy: 'livre', governance: 'sujo', housekeeper: 'Patrícia Souza' },
  { id: 'r18', number: 'UH 18', type: 'Superior', floor: 2, block: 'Torre B', capacity: 2, occupancy: 'livre', governance: 'limpo' },
  { id: 'r19', number: 'UH 19', type: 'Standard', floor: 3, block: 'Torre B', capacity: 2, occupancy: 'livre', governance: 'limpo' },
  { id: 'r20', number: 'UH 20', type: 'Suite', floor: 3, block: 'Torre B', capacity: 4, occupancy: 'livre', governance: 'limpo', housekeeper: 'Maria Silva' },
];

export const INITIAL_GUESTS: Guest[] = [
  { id: 'g1', name: 'Ana Maura Novak', document: '345.678.901-22', phone: '(41) 96666-3003', email: 'ana.novak@email.com' },
  { id: 'g2', name: 'Bruno Henrique Costa', document: '789.012.345-66', phone: '(11) 92222-7007', email: 'bruno.costa@email.com' },
  { id: 'g3', name: 'Carla Mendes Oliveira', document: '123.456.789-00', phone: '(21) 98888-1122', email: 'carla.mendes@email.com' },
  { id: 'g4', name: 'Diego Santos Pereira', document: '234.567.890-11', phone: '(31) 97777-3344', email: 'diego.santos@email.com' },
  { id: 'g5', name: 'Eliane Rocha Almeida', document: '456.789.012-33', phone: '(51) 96666-5566', email: 'eliane.rocha@email.com' },
  { id: 'g6', name: 'Felipe Augusto Lima', document: '567.890.123-44', phone: '(61) 95555-7788', email: 'felipe.lima@email.com' },
  { id: 'g7', name: 'Gabriela Nunes Ferreira', document: '678.901.234-55', phone: '(71) 94444-9900', email: 'gabriela.nunes@email.com' },
  { id: 'g8', name: 'Henrique Barbosa Silva', document: '890.123.456-77', phone: '(85) 93333-2211', email: 'henrique.barbosa@email.com' },
  { id: 'g9', name: 'Isabela Cristina Souza', document: '901.234.567-88', phone: '(19) 92222-3344', email: 'isabela.souza@email.com' },
  { id: 'g10', name: 'João Pedro Martins', document: '012.345.678-99', phone: '(47) 91111-5566', email: 'joao.martins@email.com' },
  { id: 'g11', name: 'Karina Lopes Ribeiro', document: '111.222.333-44', phone: '(48) 98888-7788', email: 'karina.lopes@email.com' },
  { id: 'g12', name: 'Lucas Eduardo Pinto', document: '222.333.444-55', phone: '(62) 97777-9900', email: 'lucas.pinto@email.com' },
];

export const INITIAL_RESERVATIONS: Reservation[] = [
  // —— Check-ins previstos (hoje 15/09) ——
  {
    id: 'res1',
    code: 'RSV-1001',
    guestId: 'g1',
    guestName: 'Ana Maura Novak',
    roomId: 'r11',
    roomNumber: 'UH 11',
    roomType: 'Chalé Master',
    checkIn: '2026-09-15',
    checkOut: '2026-09-17',
    adults: 2,
    children: 0,
    status: 'confirmada',
    origin: 'booking',
    totalAmount: 1200,
    paidAmount: 600,
    fnrhFilled: true,
    notes: 'Chegada prevista à tarde · cama extra se disponível',
  },
  {
    id: 'res3',
    code: 'RSV-1003',
    guestId: 'g3',
    guestName: 'Carla Mendes Oliveira',
    roomId: 'r02',
    roomNumber: 'UH 02',
    roomType: 'Standard',
    checkIn: '2026-09-15',
    checkOut: '2026-09-18',
    adults: 1,
    children: 0,
    status: 'confirmada',
    origin: 'direto',
    totalAmount: 540,
    paidAmount: 540,
    fnrhFilled: true,
    notes: 'Pré-pago integral · cliente VIP corporativo',
  },
  {
    id: 'res4',
    code: 'RSV-1004',
    guestId: 'g4',
    guestName: 'Diego Santos Pereira',
    roomId: 'r18',
    roomNumber: 'UH 18',
    roomType: 'Superior',
    checkIn: '2026-09-15',
    checkOut: '2026-09-16',
    adults: 2,
    children: 1,
    status: 'pendente',
    origin: 'expedia',
    totalAmount: 890,
    paidAmount: 0,
    fnrhFilled: false,
    notes: 'Aguardando confirmação de pagamento',
  },
  {
    id: 'res5',
    code: 'RSV-1005',
    guestId: 'g5',
    guestName: 'Eliane Rocha Almeida',
    roomId: 'r15',
    roomNumber: 'UH 15',
    roomType: 'Bangalô',
    checkIn: '2026-09-15',
    checkOut: '2026-09-19',
    adults: 2,
    children: 2,
    status: 'confirmada',
    origin: 'booking',
    totalAmount: 2100,
    paidAmount: 1050,
    fnrhFilled: false,
    notes: 'Família · berço no chalé',
  },
  {
    id: 'res6',
    code: 'RSV-1006',
    guestId: 'g6',
    guestName: 'Felipe Augusto Lima',
    roomId: 'r20',
    roomNumber: 'UH 20',
    roomType: 'Suite',
    checkIn: '2026-09-15',
    checkOut: '2026-09-17',
    adults: 2,
    children: 0,
    status: 'confirmada',
    origin: 'telefone',
    totalAmount: 1600,
    paidAmount: 800,
    fnrhFilled: true,
    notes: 'Lua de mel · decoração especial',
  },
  {
    id: 'res7',
    code: 'RSV-1007',
    guestId: 'g7',
    guestName: 'Gabriela Nunes Ferreira',
    roomId: 'r10',
    roomNumber: 'UH 10',
    roomType: 'Standard',
    checkIn: '2026-09-15',
    checkOut: '2026-09-16',
    adults: 1,
    children: 0,
    status: 'confirmada',
    origin: 'walkin',
    totalAmount: 280,
    paidAmount: 0,
    fnrhFilled: false,
    notes: 'Walk-in matinal',
  },
  {
    id: 'res8',
    code: 'RSV-1008',
    guestId: 'g8',
    guestName: 'Henrique Barbosa Silva',
    roomId: 'r13',
    roomNumber: 'UH 13',
    roomType: 'Chalé Master',
    checkIn: '2026-09-15',
    checkOut: '2026-09-20',
    adults: 3,
    children: 1,
    status: 'confirmada',
    origin: 'direto',
    totalAmount: 3200,
    paidAmount: 1600,
    fnrhFilled: true,
    notes: 'Grupo familiar · late checkout se possível',
  },

  // —— Hospedados (já em check-in) ——
  {
    id: 'res2',
    code: 'RSV-1002',
    guestId: 'g2',
    guestName: 'Bruno Henrique Costa',
    roomId: 'r07',
    roomNumber: 'UH 07',
    roomType: 'Superior',
    checkIn: '2026-09-14',
    checkOut: '2026-09-16',
    adults: 2,
    children: 0,
    status: 'checkin',
    origin: 'direto',
    totalAmount: 760,
    paidAmount: 400,
    fnrhFilled: true,
    accountId: 'acc1',
    notes: 'Hóspede já na casa',
  },
  {
    id: 'res9',
    code: 'RSV-1009',
    guestId: 'g9',
    guestName: 'Isabela Cristina Souza',
    roomId: 'r01',
    roomNumber: 'UH 01',
    roomType: 'Apartamento',
    checkIn: '2026-09-13',
    checkOut: '2026-09-17',
    adults: 2,
    children: 1,
    status: 'checkin',
    origin: 'booking',
    totalAmount: 1400,
    paidAmount: 700,
    fnrhFilled: true,
    accountId: 'acc2',
    notes: 'Pediu berço · sem lactose no café',
  },
  {
    id: 'res10',
    code: 'RSV-1010',
    guestId: 'g10',
    guestName: 'João Pedro Martins',
    roomId: 'r03',
    roomNumber: 'UH 03',
    roomType: 'Superior',
    checkIn: '2026-09-14',
    checkOut: '2026-09-15',
    adults: 1,
    children: 0,
    status: 'checkin',
    origin: 'expedia',
    totalAmount: 420,
    paidAmount: 420,
    fnrhFilled: true,
    accountId: 'acc3',
    notes: 'Checkout hoje',
  },
  {
    id: 'res11',
    code: 'RSV-1011',
    guestId: 'g11',
    guestName: 'Karina Lopes Ribeiro',
    roomId: 'r05',
    roomNumber: 'UH 05',
    roomType: 'Apartamento',
    checkIn: '2026-09-12',
    checkOut: '2026-09-16',
    adults: 2,
    children: 0,
    status: 'checkin',
    origin: 'telefone',
    totalAmount: 1100,
    paidAmount: 550,
    fnrhFilled: true,
    accountId: 'acc4',
    notes: 'Empresa LD Turismo',
  },
  {
    id: 'res12',
    code: 'RSV-1012',
    guestId: 'g12',
    guestName: 'Lucas Eduardo Pinto',
    roomId: 'r08',
    roomNumber: 'UH 08',
    roomType: 'Standard',
    checkIn: '2026-09-15',
    checkOut: '2026-09-18',
    adults: 2,
    children: 0,
    status: 'checkin',
    origin: 'direto',
    totalAmount: 840,
    paidAmount: 280,
    fnrhFilled: true,
    accountId: 'acc5',
    notes: 'Check-in cedo · early arrival',
  },
  {
    id: 'res13',
    code: 'RSV-1013',
    guestId: 'g3',
    guestName: 'Carla Mendes Oliveira',
    roomId: 'r12',
    roomNumber: 'UH 12',
    roomType: 'Chalé Master',
    checkIn: '2026-09-13',
    checkOut: '2026-09-18',
    adults: 4,
    children: 0,
    status: 'checkin',
    origin: 'booking',
    totalAmount: 2800,
    paidAmount: 1400,
    fnrhFilled: true,
    accountId: 'acc6',
    notes: 'Grupo de amigos · meia pensão',
  },
  {
    id: 'res14',
    code: 'RSV-1014',
    guestId: 'g6',
    guestName: 'Felipe Augusto Lima',
    roomId: 'r16',
    roomNumber: 'UH 16',
    roomType: 'Apartamento',
    checkIn: '2026-09-14',
    checkOut: '2026-09-17',
    adults: 2,
    children: 1,
    status: 'checkin',
    origin: 'expedia',
    totalAmount: 980,
    paidAmount: 0,
    fnrhFilled: false,
    accountId: 'acc7',
    notes: 'FNRH pendente · consumos em aberto',
  },
];

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: 'acc1',
    type: 'hospede',
    guestId: 'g2',
    guestName: 'Bruno Henrique Costa',
    reservationId: 'res2',
    roomId: 'r07',
    status: 'parcial',
    openedAt: '2026-09-14',
    charges: [
      { id: 'c1', description: 'Diária Superior', amount: 380, date: '2026-09-14', category: 'hospedagem' },
      { id: 'c2', description: 'Diária Superior', amount: 380, date: '2026-09-15', category: 'hospedagem' },
      { id: 'c3', description: 'Frigobar', amount: 45, date: '2026-09-14', category: 'consumo' },
      { id: 'c4', description: 'Lavanderia', amount: 35, date: '2026-09-15', category: 'servico' },
    ],
    payments: [{ id: 'p1', amount: 400, method: 'PIX', date: '2026-09-14' }],
  },
  {
    id: 'acc2',
    type: 'hospede',
    guestId: 'g9',
    guestName: 'Isabela Cristina Souza',
    reservationId: 'res9',
    roomId: 'r01',
    status: 'parcial',
    openedAt: '2026-09-13',
    charges: [
      { id: 'c5', description: 'Diária Apartamento', amount: 350, date: '2026-09-13', category: 'hospedagem' },
      { id: 'c6', description: 'Diária Apartamento', amount: 350, date: '2026-09-14', category: 'hospedagem' },
      { id: 'c7', description: 'Diária Apartamento', amount: 350, date: '2026-09-15', category: 'hospedagem' },
      { id: 'c8', description: 'Room service', amount: 89, date: '2026-09-14', category: 'consumo' },
    ],
    payments: [{ id: 'p2', amount: 700, method: 'Cartão', date: '2026-09-13' }],
  },
  {
    id: 'acc3',
    type: 'hospede',
    guestId: 'g10',
    guestName: 'João Pedro Martins',
    reservationId: 'res10',
    roomId: 'r03',
    status: 'quitada',
    openedAt: '2026-09-14',
    charges: [
      { id: 'c9', description: 'Diária Superior', amount: 420, date: '2026-09-14', category: 'hospedagem' },
    ],
    payments: [{ id: 'p3', amount: 420, method: 'PIX', date: '2026-09-14' }],
  },
  {
    id: 'acc4',
    type: 'hospede',
    guestId: 'g11',
    guestName: 'Karina Lopes Ribeiro',
    reservationId: 'res11',
    roomId: 'r05',
    status: 'parcial',
    openedAt: '2026-09-12',
    charges: [
      { id: 'c10', description: 'Diária Apartamento', amount: 275, date: '2026-09-12', category: 'hospedagem' },
      { id: 'c11', description: 'Diária Apartamento', amount: 275, date: '2026-09-13', category: 'hospedagem' },
      { id: 'c12', description: 'Diária Apartamento', amount: 275, date: '2026-09-14', category: 'hospedagem' },
      { id: 'c13', description: 'Diária Apartamento', amount: 275, date: '2026-09-15', category: 'hospedagem' },
    ],
    payments: [{ id: 'p4', amount: 550, method: 'Faturado', date: '2026-09-12' }],
  },
  {
    id: 'acc5',
    type: 'hospede',
    guestId: 'g12',
    guestName: 'Lucas Eduardo Pinto',
    reservationId: 'res12',
    roomId: 'r08',
    status: 'parcial',
    openedAt: '2026-09-15',
    charges: [
      { id: 'c14', description: 'Diária Standard', amount: 280, date: '2026-09-15', category: 'hospedagem' },
    ],
    payments: [{ id: 'p5', amount: 280, method: 'Dinheiro', date: '2026-09-15' }],
  },
  {
    id: 'acc6',
    type: 'hospede',
    guestId: 'g3',
    guestName: 'Carla Mendes Oliveira',
    reservationId: 'res13',
    roomId: 'r12',
    status: 'parcial',
    openedAt: '2026-09-13',
    charges: [
      { id: 'c15', description: 'Diária Chalé Master', amount: 560, date: '2026-09-13', category: 'hospedagem' },
      { id: 'c16', description: 'Diária Chalé Master', amount: 560, date: '2026-09-14', category: 'hospedagem' },
      { id: 'c17', description: 'Diária Chalé Master', amount: 560, date: '2026-09-15', category: 'hospedagem' },
      { id: 'c18', description: 'Meia pensão (4 pax)', amount: 320, date: '2026-09-14', category: 'consumo' },
    ],
    payments: [{ id: 'p6', amount: 1400, method: 'Cartão', date: '2026-09-13' }],
  },
  {
    id: 'acc7',
    type: 'hospede',
    guestId: 'g6',
    guestName: 'Felipe Augusto Lima',
    reservationId: 'res14',
    roomId: 'r16',
    status: 'aberta',
    openedAt: '2026-09-14',
    charges: [
      { id: 'c19', description: 'Diária Apartamento', amount: 320, date: '2026-09-14', category: 'hospedagem' },
      { id: 'c20', description: 'Diária Apartamento', amount: 320, date: '2026-09-15', category: 'hospedagem' },
      { id: 'c21', description: 'Frigobar', amount: 62, date: '2026-09-15', category: 'consumo' },
    ],
    payments: [],
  },
];
